// <auto-generated />
namespace TurkishPlatform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class son4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(son4));
        
        string IMigrationMetadata.Id
        {
            get { return "201902111021120_son4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
